#MCU = atmega32u4
F_CPU = 16000000
ARCH = AVR8
F_USB = $(F_CPU)
OPT_DEFS += -DINTERRUPT_CONTROL_ENDPOINT
#BOOTLOADER = caterina
#BOOTMAGIC_ENABLE = no       # Enable Bootmagic Lite
#MOUSEKEY_ENABLE = no      # Mouse keys
#EXTRAKEY_ENABLE = no      # Audio control and System control
#CONSOLE_ENABLE = no        # Console for debug
#COMMAND_ENABLE = no        # Commands for debug and configuration
#NKRO_ENABLE = no            # Enable N-Key Rollover
BACKLIGHT_ENABLE = no      # Enable keyboard backlight functionality
AUDIO_ENABLE = no          # Audio output
SPLIT_KEYBOARD = no
LTO_ENABLE = yes
RGBLIGHT_ENABLE = yes
DEBOUNCE_TYPE = sym_eager_pk
ENCODER_ENABLE = yes       # Enables the use of one or more encoders

